language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
script:
  - mvn test -B
  - mvn javadoc:javadoc
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: eternitywall:etqKsfod1e0lcsOFby1npMh6g
